# Generated by Django 3.0.7 on 2020-07-23 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_city_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='id',
        ),
        migrations.RemoveField(
            model_name='state',
            name='id',
        ),
        migrations.AlterField(
            model_name='city',
            name='code',
            field=models.SlugField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='state',
            name='code',
            field=models.SlugField(primary_key=True, serialize=False),
        ),
    ]
