# -*- coding: utf-8 -*-
# Migrations file example for fixing broken ManyToManyField migration from INTEGER to VARCHAR
# Generated by Django 1.10.3 on 1970-01-01 00:00
from __future__ import unicode_literals

from django.db import migrations

class Migration(migrations.Migration):
    dependencies = [
        ('frontend', '0004'),
    ]

    operations = [
        migrations.RunSQL('ALTER TABLE frontend_state ALTER code TYPE varchar(32);'),
    ]