# Generated by Django 3.0.7 on 2020-07-24 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='code',
            field=models.TextField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='state',
            name='code',
            field=models.TextField(primary_key=True, serialize=False),
        ),
    ]
