# Generated by Django 3.0.7 on 2020-07-24 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0006_auto_20200724_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='code',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
